sdk: C:/InstantRhodes/ruby/lib/ruby/gems/1.8/gems/rhodes-3.0.2
sdkversion: 3.0.1
name: MyDailyRhodes
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator4.3
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: com.rhomobile.mydailyrhodes
  BundleURLScheme: mydailyrhodes
wp:
  productid: 78d7ae00-aa1f-012e-e010-54f3feae4b1f
extensions: 
  - json
  - another-extension
android:
  emulator: GALAXYGioAndroid
  version: 2.2
